name: Documentation

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.docs.txt
      
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Deploy documentation
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Detected version: $VERSION"

          if [[ $VERSION == *"rc"* ]]; then
            echo "Release candidate detected, setting 'latest' alias"
            ALIAS=latest
          else
            echo "Stable release detected, setting 'stable' alias"
            ALIAS=stable
          fi

          echo "Deploying version $VERSION with alias $ALIAS"
          mike deploy \
            --update-aliases \
            --push \
            $VERSION $ALIAS

          mike set-default --push stable
